# .github/workflows/manual-push-to-gitlab.yml
name: Deploy to Pages

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: get full history for pushing
          ref: gh-pages

      - name: Set up Git identity
        run: |
          git config --global user.email "pages@wyliodrin.com"
          git config --global user.name "Pages Bot"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://$GITLAB_USER:$GITLAB_TOKEN@gitlab.com/<group>/<repo>.git
        env:
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

      - name: Push to GitLab
        run: |
          git push gitlab gh-pages --force
